// <auto-generated />
namespace Techno.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TechnoDB123 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TechnoDB123));
        
        string IMigrationMetadata.Id
        {
            get { return "202404240103124_TechnoDB123"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
